export const FEATURES = {
  GALLERY: 'GALLERY',
  TIMELINE: 'TIMELINE',
  CALENDAR: 'CALENDAR',
  STORIES: 'STORIES',
  CHAT: 'CHAT',
  MUSIC: 'MUSIC',
  LISTEN_TOGETHER: 'LISTEN_TOGETHER',
  HEALTH: 'HEALTH',
  GAMES: 'GAMES',
  BUDGET: 'BUDGET',
} as const;

export type FeatureKey = typeof FEATURES[keyof typeof FEATURES];

export const ALL_FEATURE_KEYS: FeatureKey[] = Object.values(FEATURES);

export const DEFAULT_ENABLED_FEATURES: FeatureKey[] = [
  FEATURES.GALLERY,
  FEATURES.TIMELINE,
  FEATURES.CALENDAR,
  FEATURES.STORIES,
  FEATURES.CHAT,
  FEATURES.MUSIC,
  FEATURES.LISTEN_TOGETHER,
];
